name: Update Experiments Config

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    name: Update Experiments Config
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update file
        run: |
          curl https://raw.githubusercontent.com/ampproject/amphtml/main/tools/experiments/experiments-config.js -o lib/experiments-config.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git commit -m "Update experiments config"
          git push
